version: "2"
services:
  "pimpmygps":
    privileged: true
    image: "coxifred/pimpmygps"
    container_name: "pimpmygps"
    restart: always
    ports:
      - "443:443"
      - "4430:4430"
    volumes:
      - ./aCore.xml:/aCore.xml
